config/routes.rb
Rails.application.routes.draw do
  get  'urls/list', to: 'urls#list'
  get  '/purple/:short_url', to: 'urls#purple'
  post 'urls/new'
  resources :urls
end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :long_url, presence: true, uniqueness: true,
    :format => { with: URI::regexp(%w(http https)) }
  validates :short_url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]
  before_action :check_admin_permission, only: [:new, :show, :edit, :update, :destroy]
  before_action :set_short_url_prefix, only: [:show, :list, :create]

  ADMIN = 0
  ALPHANUM = (('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a).join
  BASE = ALPHANUM.length
  # To get short url key with at least 5 characters
  START_OFFSET = 100000000

  # GET /urls
  # GET /urls.json
  def index
    @url = Url.new
  end

  # GET /urls/list
  # GET /urls/list.json
  def list
    @urls = Url.all
    @admin = ADMIN
  end

  # GET /urls/new
  def new
    if url_params
      create
      return
    else
      @url = Url.new
    end
  end

  # POST /urls
  # POST /urls.json
  def create
    referrer = Rails.application.routes.recognize_path(request.referrer)
    
    @url = Url.new(url_params)
    @error = nil
    result_url = Url.find_by(:long_url => @url[:long_url])

    respond_to do |format|
      if result_url.nil?
        max_id = Url.maximum(:id) || 0
        num = START_OFFSET + max_id + 1
        short_key = encode(num) 
        @url[:short_url] = short_key

        if @url.save
          @new_url = @url
          @url = Url.new(:long_url => @new_url[:long_url], :short_url => @new_url[:short_url])
          if referrer[:action] == 'index'
            format.html { render :index  }
          else
            format.html { redirect_to @new_url, notice: "URL was successfully created."}
          end
        else
          @error = @url.errors.full_messages
          if referrer[:action] == 'index'
            format.html { render :index  }
          else
            format.html { render :new }
            format.json { render json: @url.errors, status: :unprocessable_entity }
          end
        end
      else
        if referrer[:action] == 'index'
          @url[:short_url] = result_url[:short_url]
          format.html { render :index }
        else
          format.html { redirect_to result_url, notice: "Existing URL. No URL is created." }
        end
      end
    end
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/1/edit
  def edit
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'URL was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_list_url, notice: 'URL was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purple
    url = Url.find_by(:short_url => params[:short_url])

    if url.nil?
      respond_to do |format|
        format.html { render html: "Uh oh, couldn't find a link for the URL you clicked.",
          status: :bad_request }
      end
    else
      redirect_to url[:long_url], status: :moved_permanently
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      if params[:url].nil? || params[:url].empty?
      else
        return params.require(:url).permit(:long_url)
      end
    end

    def encode(num)
      str = ''

      while num > 0
        str << ALPHANUM[num.modulo(BASE)]
        num = num / BASE
      end

      return str.reverse
    end

    # NOTE: not being used for now
    def decode(str)
      num = 0
      str.each_char {|c| num = num * BASE + ALPHANUM.index(c) }
      return num;
    end

    def check_admin_permission
      unless ADMIN == 1
        respond_to do |format|
          format.html { render html: "No permission to perform this action.",
            status: :unauthorized }
        end
        return
      end
    end

    def set_short_url_prefix 
      @short_url_prefix = request.base_url + '/purple/'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortenUrl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :long_url %><br>
    <%= f.text_field :long_url, size: 75 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing URL</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back to URL List', urls_list_path %>

app/views/urls/index.html.erb
<h1>URL Shortening Application</h1>

<br>
<%= form_for(@url) do |form| %>
<label>Enter a long URL to shorten it:</label>
<br>
<%= form.text_field :long_url, size: 75 %>
<%= form.submit "Shorten" %>
<% end %>
<br>
<br>

<% if !@error && @url[:short_url] %>
<% full_short_url = "#{@short_url_prefix}#{@url[:short_url]}" %>
<label>Short URL:</label>
<%= link_to full_short_url, full_short_url, class: "purple" %>
<% end %>

<% if @error %>
<label>Note:</label>
<ul>
<% @error.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>
<% end %>

app/views/urls/list.html.erb
<p id="notice"><%= notice %></p>

<h1>URLs</h1>

<table>
  <thead>
    <tr>
      <th>Short URL</th>
      <th>Long URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= @short_url_prefix + url.short_url %></td>
        <td><%= url.long_url %></td>
        <% if @admin == 1 %>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @admin == 1 %>
<%= link_to 'New URL', new_url_path %>
<% end %>

app/views/urls/new.html.erb
<h1>New URL</h1>

<%= form_for(@url, :url => { :action => :new } ) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :long_url %><br>
    <%= f.text_field :long_url, size: 75 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back to URL List', urls_list_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Long URL:</strong>
  <%= @url.long_url %>
</p>

<p>
  <strong>Short URL:</strong>
  <%= @short_url_prefix + @url.short_url %>
</p>

<%= link_to 'Back to URL List', urls_list_path %>